openapi: "3.0.0"
info:
  version: 1.0.0
  title: AME
  description: API message
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
    url: http://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://example.com/myapi/v2
paths:
  /example:
    post:
      summary: Example API with Payload in Headers Allowed
      description: For testing
      operationId: exampleRequest
      tags:
        [tag1, tag2]
      requestBody:
        required: true
        content:
          application/json; charset=utf-8:
            schema:
              type: object
              properties:
                data:
                  type: string
      responses:
        '200':
          description: example response
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/Error'
  /example2:
    post:
      summary: Example API with Payload in Headers Allowed
      description: For testing
      operationId: exampleRequest2
      tags:
        - tag1
        - tag2
      requestBody:
        required: true
        content:
          application/json; charset=utf-8:
            schema:
              type: object
              properties:
                data:
                  type: integer
          application/json; charset=utf-16:
            schema:
              type: object
              properties:
                data:
                  type: integer
      responses:
        '200':
          description: example response
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Error'


components:
  securitySchemes:
    bearerAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: bearer
  schemas:
    Error1:
      type: object
      properties:
        "code":
          type: integer
          format: int32
        "veryLongcode":
          type: integer
          format: int32
        "verylongmessage":
          type: string
        "nest_this":
          type: string
    Error2:
      type: object
      properties:
        "nestthi_sagain":
          type: integer
          format: int32
        "veryongesMaegain":
          type: string
        "verylongmessage":
          type: string
        "nestthis":
          type: string
    Error3:
      type: object
      properties:
        "stthisaMgain":
          type: integer
          format: int32
        "veryongs_egain":
          type: string
  tags:
  - name: tag1
    description: Everything about tag1
  - name: tag2
    description: Everything about tag2
