openapi: "3.0.0"
info:
  version: 1.2.0
  title: RAP-LP
  description: OpenAPI Specification example to handle Rules for the category []Hypermedia] in the Swedish REST API-profil https://dev.dataportal.se/rest-api-profil
  license:
    name:  EUPL-1.2 license
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /example:
    post:
      summary: API request SHOULD be sent in UTF-8 format.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                  data:
                    type: string
  
      responses:
        '201':
          description: Null response
        default:
          description: unexpected er:ror
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string