openapi: "3.0.0"
info:
  version: 1.0.0
  title: SAK
  description: Säkerhet RAP-LP
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

components:
  securitySchemes:
    oAuth2Password:
      type: any
