openapi: 3.0.3
info:
  title: RAP-LP Mock API
  version: 1.0.0

paths:
  /hello:
    get:
      summary: Returns a greeting
      responses:
        "200":
          description: Hello, world!
          content:
            text/plain:
              schema:
                type: string
