# SPDX-FileCopyrightText: 2025 diggsweden/rest-api-profil-lint-processor
#
# SPDX-License-Identifier: CC0-1.0

---
    name: OpenSSF Scorecard analysis
    on:
      push:
        branches:
          - main
      schedule:
        # Weekly.
        - cron: "30 1 * * 4"
    
    permissions:
      contents: read
    
    jobs:
      scorecard-analysis:
        permissions:
          contents: read
          security-events: write
          id-token: write
        uses: diggsweden/.github/.github/workflows/openssf-scorecard.yml@main